spring:
  application:
    name: scheduler

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        connection:
          provider_disables_autocommit: true

logging:
  level:
    org:
      springframework:
        ampq:
          rabbit:
            core:
              RabbitAdmin: DEBUG

server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param

amqp:
  exchange:
    scheduler: scheduler-agenda
    admin: admin-agenda
  queue:
    scheduler: scheduler-queue
  routingkey:
    scheduler: scheduler-key
    admin: admin-key

redis:
  hostname: localhost
  port: 6379

api:
  user-info: https://user-info.herokuapp.com/users/

management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, conditions, scheduledtasks


scheduler-config:
  delay: -60000
