spring:
  application:
    name: admin

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        connection:
          provider_disables_autocommit: true
  datasource:
    url: jdbc:mysql://localhost:3307/dbs
    username: dbsadmin
    password: dbsadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false

logging:
  level:
    org:
      springframework:
        ampq:
          rabbit:
            core:
              RabbitAdmin: DEBUG

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param

amqp:
  exchange:
    scheduler: scheduler-agenda
    admin: admin-agenda
  queue:
    admin: admin-queue;
  routingkey:
    scheduler: scheduler-key
    admin: admin-key
