spring:
  application:
    name: admin

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        connection:
          provider_disables_autocommit: true
  datasource:
    url: jdbc:mysql://localhost:3307/dbs
    username: dbsadmin
    password: dbsadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:init-schema.sql
    initialization-mode: always
    hikari:
      auto-commit: false

logging:
  level:
    org:
      springframework:
        ampq:
          rabbit:
            core:
              RabbitAdmin: DEBUG

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on-param

amqp-config:
  scheduler-exchange: scheduler-agenda
  admin-exchange: admin-agenda
  admin-queue: admin-queue
  scheduler-routing-key: scheduler-key
  admin-routing-key: admin-key
