server:
  port: 8080

spring:
  application:
    name: GatewayService
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      enabled: true
      discovery:
        # Get only services that are passing the health check
        query-passing: true
    gateway:
      routes:
        - id: users
          uri: http://localhost:8082/
          predicates:
            - Path=/users, /users/**
        - id: wavestream
          uri: http://localhost:8083/
          predicates:
            - Path=/wavestream, /wavestream/**
        - id: analytics
          uri: http://localhost:8090/
          predicates:
            - Path=/analyticsclient, /analyticsclient/**
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST

logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            handler:
              predicate: trace
